compile: helloWorld.c
	# gcc -o helloWorld helloWorld.c -lm -O3 -lpthread -g
    # gcc -o primesNumber primesNumber.c -lm -O3 -lpthread -g
	gcc -o addVectors addVectors.c -lm -O3 -lpthread -g

clean:
	# rm helloWorld
	# rm primesNumber
	rm addVectors

	# gcc -o addVectors addVectors.c –lpthread –lrt